<a href="https://colab.research.google.com/github/DataBaeDev/Python-Odds-and-Ends/blob/main/NYC_Open_Data_API.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Accessing data using the [NYC Open Data](https://opendata.cityofnewyork.us/) API

**Dataset details as of June 2024**<br>
Dataset Identifier: w2pb-icbu<br>
Total Rows: 606260<br>
Source Domain: [data.cityofnewyork.us](data.cityofnewyork.us)<br>
Created: 12/11/2018<br>
Last Updated: 7/3/2023<br>
Category: City Government<br>
Attribution: Department of Finance<br>
Owner: NYC OpenData<br>
Endpoint Version: 2.1<br>

Click [here](https://dev.socrata.com/foundry/data.cityofnewyork.us/w2pb-icbu) for more info on the specific dataset.

In [ ]:
# install new library
!pip install sodapy

In [2]:
import pandas as pd
from sodapy import Socrata

In [3]:
# Initialize the client, without using an api token
client = Socrata("data.cityofnewyork.us", None)
dataset_id = "w2pb-icbu" #NYC Citywide Annualized Calendar Sales

WARNING:root:Requests made without an app_token will be subject to strict throttling limits.

In [4]:
# Function to collect all records from the api and append to a dataframe
# Use an api token above to increase the number of records that can be obtained

def records_to_df(dataset_id):
    offset = 0
    limit = 50000
    records = []

    while True:
        results = client.get(dataset_id, limit=limit, offset=offset)
        if not results:
            break
        records.extend(results)
        offset += limit
        #print(f"{len(records)} records retrieved...")

    # Convert the list of records to a pandas DataFrame
    df = pd.DataFrame(records)
    return df

In [5]:
# Call function and save results to a dataframe
results_df = records_to_df(dataset_id)

50000 records retrieved...
100000 records retrieved...
150000 records retrieved...
200000 records retrieved...
250000 records retrieved...
300000 records retrieved...
350000 records retrieved...
400000 records retrieved...
450000 records retrieved...
500000 records retrieved...
550000 records retrieved...
600000 records retrieved...
606260 records retrieved...

In [6]:
# Print the size of the final dataframe as well as a few sample records
print("Final dataframe shape is ", results_df.shape)
results_df.sample(7)

Final dataframe shape is  (606260, 30)

,borough,neighborhood,building_class_category,tax_class_as_of_final_roll,block,lot,building_class_as_of_final,address,zip_code,residential_units,...,longitude,community_board,council_district,census_tract,bin,bbl,nta,apartment_number,census_tract_2020,nta_code
134130,QUEENS,JAMAICA HILLS,10 COOPS - ELEVATOR APARTMENTS,2,9860,40,D4,84-50 169TH STREET,11432,NaN,...,-73.795284,408,24,454,4210913,4098600040,Briarwood-Jamaica Hills,304,NaN,NaN
38050,3,GRAVESEND,02 TWO FAMILY DWELLINGS,1,6913,7,B1,2707 CROPSEY AVENUE,11214,2,...,-73.989775,313,43,314,3187169,3069130007,Gravesend,NaN,NaN,NaN
509609,5,NEW BRIGHTON,21 OFFICE BUILDINGS,4,33,29,O7,187 VICTORY BOULEVARD,10301,0,...,-74.082106,501,49,11,5000663,5000330029,West New Brighton-New Brighton-St. George,NaN,NaN,NaN
170806,MANHATTAN,UPPER WEST SIDE (59-79),10 COOPS - ELEVATOR APARTMENTS,2,1184,87,D4,304 WEST 75TH STREET,10023,NaN,...,-73.983563,107,6,163,1031010,1011840087,Upper West Side,NaN,NaN,NaN
578796,4,RICHMOND HILL,02 TWO FAMILY DWELLINGS,1,9254,22,S2,116-09 JAMAICA AVENUE,11418,2,...,-73.833009,409,29,NaN,4193397,4092540022,NaN,NaN,132,QN0902
586037,1,CHINATOWN,47 CONDO NON-BUSINESS STORAGE,4,172,1526,RS,"50 FRANKLIN STREET, S27B",10013,NaN,...,-74.0025,101,1,31,1088222,1001727504,NaN,S27B,31,MN0102
278477,1,HARLEM-UPPER,29 COMMERCIAL GARAGES,4,2067,120,G7,843 ST NICHOLAS AVENUE,10031,0,...,-73.942156,109,7,23501,1000000,1020670020,Hamilton Heights,NaN,NaN,NaN